export 'CategoryPage.dart';
export 'CreateOrderPage.dart';
export 'HistoryPage.dart';
export 'ModifierPage.dart';
export 'OrderDescription.dart';
export 'ProductPage.dart';
export 'UserPage.dart';
export 'OutletPage.dart';
export 'DiscountPage.dart';
